quadraticEquation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('quadraticEquationApp/', include('quadraticEquationApp.urls')),
    path('admin/', admin.site.urls),
]

quadraticEquationApp/urls.py
from . import views
from django.urls import path

app_name = 'quadraticEquationApp'
urlpatterns = [
    path('', views.equation_input, name='equation_input'),
    path('<int:equation_id>/', views.calculate, name='calculate'),
    path('all/', views.eq_list, name='eqList'),
    path('save/', views.save_and_list, name='save')
]

quadraticEquationApp/models.py
from django.db import models

# Create your models here.


class Equation(models.Model):
    a = models.FloatField()
    b = models.FloatField()
    c = models.FloatField()
    x1 = models.FloatField()
    x2 = models.FloatField()

    x1.null = True
    x2.null = True

quadraticEquationApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.template import loader
from django.shortcuts import get_list_or_404
from django.urls import reverse
from .models import Equation


# Create your views here.

def equation_input(request):
    equation = Equation()
    template = loader.get_template('quadraticEquationApp/form.html')
    context = {'equation': equation}
    return HttpResponse(template.render(context, request))


def eq_list(request):
    list = Equation.objects.order_by('id')
    template = loader.get_template('quadraticEquationApp/eqList.html')
    context = {'eq_list': list}

    return HttpResponse(template.render(context, request))


def save_and_list(request):
    if request.method == "POST":
        a = request.POST['a']
        b = request.POST['b']
        c = request.POST['c']
        if a != '' and b != '' and c != '':
            eq = Equation(a=a, b=b, c=c)
            eq.save()
        else:
            return render(request, 'quadraticEquationApp/form.html', {'error_message': "Fill in all the fields"})

    return HttpResponseRedirect(reverse('quadraticEquationApp:eqList'))


def calculate(request, equation_id):
    e = Equation.objects.get(pk=equation_id)
    D = e.b ** 2 - 4 * e.a * e.c

    if D >= 0:
        e.x1 = (-e.b + D ** 0.5) / (2 * e.a)
        e.x2 = (-e.b - D ** 0.5) / (2 * e.a)
        e.save()

    return HttpResponseRedirect(reverse('quadraticEquationApp:eqList'))


class EqList(generic.ListView):
    template_name = 'quadraticEquationApp/eqList.html'
    context_object_name = 'equations'

    def get_queryset(self):
        return Equation.objects.order_by('id')[:]

quadraticEquationApp/templates/quadraticEquationApp/eqList.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quadraticEquationApp/table.css' %}">
    <meta charset="UTF-8">
    <title>List of equations</title>
</head>
<body>
<h1>List of equations</h1>

<table>
{% for equation in eq_list %}
   <tr>
    <td>{{equation.a}}x^2 + {{equation.b}}x + {{equation.c}}</td>
       <td>
        {% if equation.x1 == null and equation.x2 == null %}
           no solution
        {% else %}
            {% if equation.x1 == equation.x2 %}
                x1 = x2 = {{equation.x1|floatformat:2}}
            {% else %}
                x1 = {{equation.x1|floatformat:2}}, x2 = {{equation.x2|floatformat:2}}
            {% endif %}
        {% endif %}
       </td>
       <td>
           <form action="{% url 'quadraticEquationApp:calculate' equation.id %}" method="post">
               {% csrf_token %}
               <button type="submit">Вычислить</button>
           </form>
       </td>
   </tr>
{% endfor %}
</table>

<a href="{% url 'quadraticEquationApp:equation_input' %}">Back to equation input form</a>
</body>
</html>

quadraticEquationApp/templates/quadraticEquationApp/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quadraticEquationApp/form.css' %}">
    <meta charset="UTF-8">
    <title>Enter new equation</title>
</head>
<body>
<h1>Equation input form</h1>

{% if error_message %}<p>{{ error_message }}</p>{% endif %}

<form action="{% url 'quadraticEquationApp:save' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td></td>
            <td align="center">ax^2 + bx + c = 0</td>
        </tr>
        <tr>
            <td>a</td>
            <td><input type="number" step="any" name="a"></td>
        </tr>

        <tr>
            <td>b</td>
            <td><input type="number" step="any" name="b"></td>
        </tr>

        <tr>
            <td>c</td>
            <td><input type="number" step="any" name="c"></td>
        </tr>

        <tr>
            <td></td>
            <td><input type="submit" value="Save equation"></td>
        </tr>
    </table>
</form>

<a href="{% url 'quadraticEquationApp:eqList' %}">See all equations</a>
</body>
</html>